feat: v2
jkusa/ember-cli-clipboard pull request #422
Opened 2024-10-23 07:46 UTC by aklkv

2025-07-12 23:52 UTC, aklkv commented
@jkusa I think I am done here 👍🏻

2025-07-25 00:15 UTC, aklkv commented
@jkusa any update, can I do anything to get this merged and released?

2025-08-01 01:34 UTC, jkusa requested changes
Thank you @aklkv for this PR 🙏 Left a few comments. Also, I would like to rev the doc site a bit, but want to get this PR landed. Can you please switch the PR target to `next`?

2025-08-01 01:34 UTC, jkusa commented on CONTRIBUTING.md
> +- `cd workspace-root`
```suggestion
- `cd ember-cli-clipboard`
```

2025-08-01 01:34 UTC, jkusa commented on README.md
> +# workspace-root
Can we revert this to the original version?

2025-08-01 01:34 UTC, jkusa commented on README.md
> -- `buttonType` - string value of the button's [type attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#Attributes) (for Ember < `3.25.x`, see below)
Probably a good time to remove this.

2025-08-01 01:34 UTC, jkusa commented on addon/src/modifiers/clipboard.ts
> +  Args: {
Can we update this based on the definition here: https://github.com/jkusa/ember-cli-clipboard/blob/73790700372a540bed1213a4bcf078edcc5164d9/index.d.ts

2025-08-01 01:34 UTC, jkusa commented on addon/src/modifiers/clipboard.ts
> +  if (!isBlank(text) && text) {
what case does the `&& text` catch that `isBlank` doesn't?

2025-08-01 01:34 UTC, jkusa commented on addon/src/modifiers/clipboard.ts
> +            action();
Yes, previously we were splatting through the `arguments`

https://github.com/jkusa/ember-cli-clipboard/blob/09ad9ad9d09c042372bc3f6a6e58971ac1db3b97/addon/modifiers/clipboard.js#L57

2025-08-01 03:33 UTC, aklkv commented on addon/src/modifiers/clipboard.ts
> +  Args: {
I tried but ClipboardJS types are bit wrong 

<img width="618" height="144" alt="Screenshot 2025-07-31 at 8 33 05 PM" src="https://github.com/user-attachments/assets/32565fc6-97e9-4883-868f-da95e4f9419a" />

<img width="981" height="301" alt="Screenshot 2025-07-31 at 8 33 26 PM" src="https://github.com/user-attachments/assets/fbb43328-de18-4c3b-86fd-c4269b2deb99" />

2025-08-01 03:35 UTC, aklkv commented on addon/src/modifiers/clipboard.ts
> +  if (!isBlank(text) && text) {
I do not think that isBlack handles or exposes correct types to handle undefined 

<img width="1314" height="307" alt="Screenshot 2025-07-31 at 8 34 36 PM" src="https://github.com/user-attachments/assets/e1acc5c7-e854-46ce-98f1-08d4e1286ecb" />

2025-10-04 08:49 UTC, aklkv commented
@jkusa could we possibly merge this?

2026-04-16 03:24 UTC, aklkv commented
@jkusa 👋🏻 any chance we can move this along?

2026-05-30 00:12 UTC, closed without merging